Algoritmo "ESTRUTURA_REPETIÇÃO_ENQUANTO_PARTE_2"
// 
// Contar até 20.
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/02/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 0
ENQUANTO cont < 20 faca
         cont <- cont + 2
         EscrevaL(cont)
FIMENQUANTO

EscrevaL(" Fim do programa!")

Fimalgoritmo